import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";
import header from "@/components/header";
import Header from "@/components/header";

const inter= Inter({subsets: ["latin"]});
export const metadata: Metadata = {
  title: "AI Career Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} `}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            <Header/>
            <main className="flex min-h-screen flex-col items-center justify-between p-24">{children}</main>

            <footer className="flex items-center justify-center w-full h-24 border-t">
              <div>
                <p>Sujan</p>
              </div>
              </footer>
            </ThemeProvider>


      </body>
    </html>
    </ClerkProvider>
  );
}
